import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    // src/components/ui/ is generated by the shadcn CLI and must never be
    // hand-edited (AGENTS.md) — so a lint rule this project cannot act on
    // without violating that rule is turned off there, rather than left
    // to be silenced with an inline comment the next `shadcn add`
    // overwrite would erase.
    //
    // Scoped to this one rule, and only here: `carousel.tsx` calls its
    // own onSelect() inside an effect to read Embla's initial slide.
    // Embla is exactly the "external system" the rule's own
    // documentation names as the legitimate case, and the alternative —
    // not syncing on mount — would leave the position indicator claiming
    // slide 1 whatever slide is actually shown.
    files: ["src/components/ui/**"],
    rules: { "react-hooks/set-state-in-effect": "off" },
  },
]);

export default eslintConfig;
