import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { renderToStaticMarkup } from "react-dom/server";
import { describe, expect, it, vi } from "vitest";

// next/font/google needs the Next.js compiler transform, unavailable under
// Vitest — mock it with the shape the layout actually reads (`.variable`).
vi.mock("next/font/google", () => ({
  Geist: () => ({ variable: "--font-geist-sans" }),
  Geist_Mono: () => ({ variable: "--font-geist-mono" }),
}));

describe("RootLayout shell", () => {
  it("declares the app in French, not the create-next-app defaults", async () => {
    const { metadata } = await import("./layout");

    expect(metadata.title).not.toBe("Create Next App");
    expect(metadata.description).not.toBe("Generated by create next app");
    expect(metadata.title).toBe("morpho");
  });

  it("renders <html lang=\"fr\"> and a pre-paint dark-mode script", async () => {
    const { default: RootLayout } = await import("./layout");
    const html = renderToStaticMarkup(
      RootLayout({ children: <div>content</div> }),
    );

    expect(html).toContain('lang="fr"');
    expect(html).not.toContain('lang="en"');
    // The theme is applied by class (design-system.md §Thème), before paint,
    // from the system preference — not a media query in CSS.
    expect(html).toMatch(/<script[^>]*>[^<]*prefers-color-scheme[^<]*<\/script>/);
    expect(html).toMatch(/classList\.add\(["']dark["']\)/);
  });

  it("fixes the broken --font-sans self-reference in globals.css", () => {
    const css = readFileSync(
      resolve(import.meta.dirname, "globals.css"),
      "utf8",
    );

    expect(css).not.toContain("--font-sans: var(--font-sans)");
    expect(css).toContain("--font-sans: var(--font-geist-sans)");
  });

  // Plan task 9, decision 12: the Toaster mounts exactly once, at the root
  // layout — no authenticated layout exists to host it instead, and s03
  // isn't the story to build one just for this. sonner's <Toaster/> only
  // renders its styled [data-sonner-toaster] container post-mount (an
  // internal useState(false) + useEffect guard), so renderToStaticMarkup
  // — which never runs effects — can't observe it; the source is what
  // proves exactly one is wired in, the same way the boilerplate-purge
  // test in src/app/page.test.tsx asserts on raw source.
  it("mounts exactly one <Toaster />, imported from the shadcn sonner primitive", () => {
    const source = readFileSync(
      resolve(import.meta.dirname, "layout.tsx"),
      "utf8",
    );

    expect(source).toContain('import { Toaster } from "@/components/ui/sonner"');
    expect(source.match(/<Toaster\s*\/>/g)).toHaveLength(1);
  });

  // Plan s06 task 8: the condition src/app/(home)/loading.tsx's skeleton
  // depends on — the layout must never read the session itself, or
  // Next never gets to show the loading fallback while the page's own
  // read is in flight (research trap 17: session reads belong in the
  // page, not the layout).
  it("never imports @/lib/auth or next/headers — the session is read in the page, not the layout", () => {
    const source = readFileSync(
      resolve(import.meta.dirname, "layout.tsx"),
      "utf8",
    );

    expect(source).not.toContain("@/lib/auth");
    expect(source).not.toContain("next/headers");
  });

  // s10 plan task 6, decision 17: the two defaults that would each work
  // AGAINST this story (trap 3) — cacheOnNavigation posts CACHE_URLS for
  // every visited page (a user-data caching mechanism outside the
  // routing table just written), reloadOnOnline drops whatever the user
  // was mid-typing when the network returns (criterion 5). Both must be
  // explicitly false; a maison router.refresh() (task 7) replaces the
  // reload. Source-based, same motif as the Toaster assertion above:
  // SerwistProvider renders no DOM of its own to assert on.
  it("mounts SerwistProvider with cacheOnNavigation and reloadOnOnline both explicitly false", () => {
    const source = readFileSync(
      resolve(import.meta.dirname, "layout.tsx"),
      "utf8",
    );

    expect(source).toContain(
      'import { SerwistProvider } from "@serwist/turbopack/react"',
    );
    expect(source).toMatch(/<SerwistProvider[\s\S]*?swUrl="\/serwist\/sw\.js"/);
    expect(source).toMatch(/<SerwistProvider[\s\S]*?cacheOnNavigation=\{false\}/);
    expect(source).toMatch(/<SerwistProvider[\s\S]*?reloadOnOnline=\{false\}/);
  });

  it("renders without crashing with SerwistProvider mounted (no serviceWorker under jsdom, no window.serwist)", async () => {
    const { default: RootLayout } = await import("./layout");

    expect(() =>
      renderToStaticMarkup(RootLayout({ children: <div>content</div> })),
    ).not.toThrow();
  });
});
